name: "Go Test - Single"
description: Runs Go tests on the codebase via gotestsum and generates reports.

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: stable
          cache: true
      - name: Make reports dir
        run: mkdir -p '${{ runner.temp }}/reports'
      - name: Run tests
        run: |
          go tool gotestsum \
            --packages ./... \
            --junitfile '${{ runner.temp }}/reports/run-${{ github.run_number }}.junit.xml' \
            --jsonfile '${{ runner.temp }}/reports/run-${{ github.run_number }}.json' \
            --format github-actions \
            --format-icons text
      - name: Upload test results
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: TestReports
          path: |
            ${{ runner.temp }}/reports/*.json
            ${{ runner.temp }}/reports/*.junit.xml
          retention-days: 7
        if: always()

  test-passed:
    name: Tests Passed
    runs-on: ubuntu-latest
    if: always()
    needs: test
    steps:
      - name: Fail because of test failure
        if: needs.test.result != "success"
        run: exit 1

  collect-reports:
    name: Collect Test Reports
    if: always()
    needs: [ "test" ]
    runs-on: ubuntu-latest
    steps:
      - name: Download test reports
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: TestReports
          path: ${{ runner.temp }}/reports
      - name: Generate test summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: ${{ runner.temp }}/reports/run-${{ github.run_number }}*.junit.xml
          show: fail, skip
      - name: Prune old reports
        run: |
          ls -lhR '${{ runner.temp }}/reports'
          find '${{ runner.temp }}/reports' -mindepth 1 -mtime +30 -delete
          ls -lhR '${{ runner.temp }}/reports'
      - name: Save test reports
        uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: "${{ runner.temp }}/reports"
          key: "test-reports-${{ github.run_number }}"
