name: Kustomize Render

on:
  workflow_call:
    inputs:
      ref:
        description: The Git ref to render
        type: string
        required: false
        default: ""
      path:
        description: The path to the Kustomization to render
        type: string
        required: true
    outputs:
      manifests:
        description: The rendered Kubernetes manifests
        value: "${{ jobs.render.outputs.manifests }}"
      images-lock:
        description: The images lock file
        value: "${{ jobs.render.outputs.images-lock }}"

jobs:
  kustomize:
    runs-on: ubuntu-latest
    name: Render Kustomization - ${{ inputs.path }} at ${{ inputs.ref }}
    outputs:
      manifests: "${{ steps.render.outputs.manifests }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: "${{ inputs.ref }}"
          path: kustomize-${{ inputs.ref }}
      - name: Install mise
        uses: jdx/mise-action@c5d0c300fa141a481a2fce49a31e5bacbe65125e # main
        with:
          mise_toml: |
            [tools]
              kbld = "0.45.0"
              kustomize = "5.6.0"
              helm = "3.17.2"
          experimental: true
        env:
          GITHUB_TOKEN: "${{ github.token }}"
      - name: Make workdir
        id: workdir
        run: |
          mkdir -p '${{ runner.temp }}/kustomize-${{ inputs.ref }}'
          echo "workdir=${{ runner.temp }}/kustomize-${{ inputs.ref }}" >>"${GITHUB_OUTPUT}"
      - name: Render manifests
        id: render
        run: |
          # Render the manifests and resolve the images
          kustomize build \
            --enable-alpha-plugins \
            --network \
            --load-restrictor LoadRestrictionsNone \
            'kustomize-${{ inputs.ref }}/${{ inputs.path }}' |
          kbld \
            -f - \
            --build=false \
            --sort=false \
            --yes \
            --imgpkg-lock-output '${{ steps.workdir.outputs.workdir }}/images.yml' >'${{ steps.workdir.outputs.workdir }}/manifests.yaml'

          # Set the output. Multi-line string pattern from here:
          # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings
          {
            echo 'manifests<<MANIFESTYAML'
            cat '${{ steps.workdir.outputs.workdir }}/manifests.yaml'
            echo 'MANIFESTYAML'
          } >>"${GITHUB_OUTPUT}"
          {
            echo 'images-lock<<IMAGESLOCKYAML'
            cat '${{ steps.workdir.outputs.workdir }}/images.yml'
            echo 'IMAGESLOCKYAML' 
          } >>"${GITHUB_OUTPUT}"
