name: Render Kube App

on:
  workflow_call:
    inputs:
      path: 
        type: string
        description: The path to the Kustomization to render relative to the root of the repository
        required: true
      create-bundle:
        type: boolean
        description: Whether to create an imgpkg bundle
        required: false
        default: false

jobs:
  render-head:
    name: Render HEAD
    uses: ./.github/workflows/kustomize.yml
    with:
      ref: "${{ github.head_ref }}"
      path: "${{ inputs.path }}"

  render-base:
    if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
    name: Render Base
    uses: ./.github/workflows/kustomize.yml
    with:
      ref: "${{ github.base_ref }}"
      path: "${{ inputs.path }}"

  diff-resources:
    if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
    needs: [render-head, render-base]
    name: Generate Kubernetes Resource Diff
    uses: ./.github/workflows/diff-kubernetes-manifests.yml
    with:
      previous: "${{ needs.render-base.outputs.manifests }}"
      next: "${{ needs.render-head.outputs.manifests }}"

  show-resources:
    needs: [render-head]
    name: Show Kubernetes Resources
    runs-on: ubuntu-latest
    steps:
      - name: Show resources
        # Do things with a multi-line bash string to avoid issues with single and double quotes.
        run: |
          cat <<EOF >"${GITHUB_STEP_SUMMARY}"
          # Kubernetes Resources

          <details>

          <summary>Click to expand</summary>

          ```yaml
          ${{ needs.render-head.outputs.manifests }}
          ```

          </details>
          EOF
  
  diff-images-lock:
    if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
    needs: [render-head, render-base]
    name: Generate Images Lock Diff
    uses: ./.github/workflows/diff-images-lock.yml
    with:
      previous: "${{ needs.render-base.outputs.images-lock }}"
      next: "${{ needs.render-head.outputs.images-lock }}"

  show-images-lock:
    needs: [render-head]
    name: Show Images lockfile
    runs-on: ubuntu-latest
    steps:
      - name: Show lockfile
        run: |
          cat <<EOF >"${GITHUB_STEP_SUMMARY}"
          # Images

          <details>

          <summary>Click to expand</summary>

          ```yaml
          ${{ needs.render-head.outputs.images-lock }}
          ```

          </details>
          EOF

  package:
    if: inputs.create-bundle
    needs: [render-head]
    name: Generate Imgpkg Bundle
    uses: ./.github/workflows/create-imgpkg-bundle.yml
    with:
      manifests: "${{ needs.render-head.outputs.manifests }}"
      images-lock: "${{ needs.render-head.outputs.images-lock }}"
