name: Render Kube App

on:
  workflow_call:
    inputs:
      path: 
        type: string
        description: The path to the Kustomization to render relative to the root of the repository
        required: true

jobs:
  render-head:
    name: Render HEAD
    uses: ./.github/workflows/kustomize.yml
    with:
      ref: "${{ github.head_ref }}"
      path: "${{ inputs.path }}"

  render-base:
    if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
    name: Render Base
    uses: ./.github/workflows/kustomize.yml
    with:
      ref: "${{ github.base_ref }}"
      path: "${{ inputs.path }}"

  diff-resources:
    if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
    needs: [render-head, render-base]
    name: Generate Kubernetes Resource Diff
    uses: ./.github/workflows/diff-kubernetes-manifests.yml
    with:
      previous: "${{ needs.render-base.outputs.manifests }}"
      next: "${{ needs.render-head.outputs.manifests }}"

  show-resources:
    needs: [render-head]
    name: Show Kubernetes Resources
    runs-on: ubuntu-latest
    steps:
      - name: Show resources
        run: |
          {
            echo "# Kubernetes Resources"
            echo ''
            echo '<details>'
            echo '<summary>Click to expand</summary>'
            echo '```yaml'
            echo -n '${{ needs.render-head.outputs.manifests }}'
            echo '```'
            echo '</details>'
          } >>"${GITHUB_STEP_SUMMARY}"
  
  # diff-images-lock:
  #   if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
  #   depends_on: [render-head, render-base]
  #   name: Generate Images Lock Diff
  #   uses: ./.github/workflows/diff-images-lock.yml
  #   with:
  #     previous: "${{ needs.render-base.outputs.images-lock }}"
  #     next: "${{ needs.render-head.outputs.images-lock }}"

  # package:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
